### ISSUE TITLE
关于增量蒸馏的一些问题

### ISSUE THREAD

**Issue by lainanhui** [seukgcode/IncDE#1]
你好作者，不好意思打扰您，我在阅读论文和代码的时候，蒸馏使用到old.data.ent_embedding的部分是上一个snapshot学习得到的embedding的部分是吗？

**Comment by ljj-007** [comment]
是的

**Comment by lainanhui** [comment]
> 是的

好的谢谢作者，还有一个小问题就是，我复现了您的工作在ENTITY数据集上，得到如下结果，snapshot=4，MRR=0.254就是对应的您论文上的0.253结果对吗，不知道这样理解对不对呢
![Uploading image.png…]()

**Comment by lainanhui** [comment]
好的谢谢作者，还有一个小问题就是，我复现了您的工作在ENTITY数据集上，得到如下结果，snapshot=4，MRR=0.254就是对应的您论文上的0.253结果对吗，不知道这样理解对不对呢


![image](https://github.com/user-attachments/assets/4a6fa77a-d325-4ccc-b3b6-aa276200202f)

**Comment by ljj-007** [comment]
是的。
